ALTER TABLE users ADD COLUMN IF NOT EXISTS "upiId" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "bankAccountNumber" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "bankIfsc" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "bankAccountName" TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "bankName" TEXT;
